"""
constants shared by different modules
"""

WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

# a message that matches this regex was generated by a Facebook game
# note that this can get some false positives
GAME_REGEX = "^.+ scored (1 point|\d+ points) (playing|in) .+\.$|" + \
    "^.+ set a new personal best of (1 point|\d+ points) in .+\.$|" + \
    "^(You are|.+ is) now in first place in .+\.$|" + \
    "^.+ challenged you in .+\.$|" + \
    "^You challenged .+ in .+\.$|" + \
    "^.+ set the new high score of (1 point|\d+ points) playing .+\.$"

# matches plan updates
PLAN_UPDATE_REGEX = "^.+ started a plan\.$|" + \
    "^.+ named the plan .+\.$|" + \
    "^.+ deleted the plan for .+ at .+\.$"

# matches chat updates (nicknames, emojis, colours, etc.)
CHAT_UPDATE_REGEX = "^.+ set the emoji to .+\.$|" + \
    "^.+ set your nickname to .+\.$|" + \
    "^You set the nickname for .+ to .+\.$|" + \
    "^.+ changed the chat colors\.?$"

# matches call updates
CALL_UPDATE_REGEX = "^You and .+ can now see each other\.$"

# Facebook automatically converts these text emoticons to emojis
EMOJI_SHORTCUTS = {
    ':(': '😞', ':[': '😞', ':-(': '😞', '=(': '😞',
    ':)': '🙂', ':]': '🙂', ':-)': '🙂',
    '>:(': '😠', ' >:-(': '😠', '>:O': '😠', '>:-O': '😠', '>:o': '😠', '>:-o': '😠',
    ':-D': '😃', ':D': '😃', '=D': '😃',
    ":'(": '😢',
    ':O': '😮', ':-O': '😮', ':o': '😮', ':-o': '😮',
    '<3': '❤',
    ';)': '😉', ';-)': '😉',
    ':-P': '😛', ':P': '😛', ':-p': '😛', ':p': '😛', '=P': '😛',
    ':/': '😕', ':-/': '😕', ':\\': '😕', ':-\\': '😕',
    ':*': '😗', ':-*': '😗',
    '=)': '😊', '^_^': '😊',
    '8)': '😎', '8-)': '😎', 'B-)': '😎', 'B)': '😎',
    'O:)': '😇', 'O:-)': '😇',
    '3:)': '😈', '3:-)': '😈',
    '-_-': '😑',
    ':|': '😐', ':-|': '😐',
    ';P': '😜', ';-P': '😜', ';p': '😜', ';-p': '😜',
    'T_T': '😭'
}
